apply plugin: 'java-library'
apply plugin: 'maven-publish'
apply plugin: 'architectury-plugin'
apply plugin: 'dev.architectury.loom'
apply plugin: 'com.gradleup.shadow'

architectury {
    platformSetupLoomIde()
    fabric()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    shadowCommon {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modApi "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"
    modApi "dev.architectury:architectury-fabric:${rootProject.architectury_version}"

    common(project(path: ':common', configuration: 'namedElements')) {
        transitive = false
    }
    shadowCommon(project(path: ':common', configuration: 'transformProductionFabric')) {
        transitive = false
    }
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            minecraft_version    : rootProject.minecraft_version,
            fabric_loader_version: rootProject.fabric_loader_version,
            fabric_api_version   : rootProject.fabric_api_version,
            architectury_version : rootProject.architectury_version,
            mod_id               : rootProject.mod_id,
            mod_name             : rootProject.mod_name,
            mod_license          : rootProject.mod_license,
            mod_version          : rootProject.mod_version,
            mod_authors          : rootProject.mod_authors,
            mod_description      : rootProject.mod_description,
            mod_display_url      : rootProject.mod_display_url,
            mod_issue_tracker    : rootProject.mod_issue_tracker,
            mod_package          : rootProject.maven_group,
    ]
    inputs.properties replaceProperties

    filesMatching('fabric.mod.json') {
        expand replaceProperties
    }
}

tasks.named('shadowJar').configure {
    archiveClassifier = 'dev-shadow'
    configurations = [project.configurations.shadowCommon]
    exclude 'META-INF/neoforge.mods.toml'
}

tasks.named('remapJar').configure {
    inputFile = tasks.named('shadowJar').flatMap { it.archiveFile }
    dependsOn tasks.named('shadowJar')
}

tasks.named('sourcesJar', Jar).configure {
    def commonSources = project(':common').tasks.named('sourcesJar', Jar)
    dependsOn commonSources
    from commonSources.map { zipTree(it.archiveFile.get().asFile) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}
