org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Template Properties
java_version=21
enabled_platforms=fabric,neoforge

# Minecraft Properties
minecraft_version=1.21.1
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Dependency Versions
architectury_version=13.0.8
fabric_loader_version=0.19.2
fabric_api_version=0.116.12+1.21.1
neo_version=21.1.219
modmenu_version=11.0.4

# ToucanLib
enable_toucanlib=true
useLocalToucanLib=false
toucanlib_version=0.1.4
toucanlib_modrinth_slug=toucan
toucanlib_neoforge_version=0.1.4-neoforge
toucanlib_curse_project_id=1542666
toucanlib_curse_file_id=8089151

# Loader Ranges
minecraft_version_range=[1.21.1]
loader_version_range=[1,)

## Mod Properties
mod_id=villagerretaliation
mod_name=Villager Retaliation!
mod_authors=jvn
mod_license=GNU General Public License v3.0
mod_version=1.0.0-beta.4
maven_group=com.jvn.villagerretaliation
archives_base_name=villager_retaliation
mod_description=Makes villagers fight back and respond more dynamically when threatened.
mod_display_url=https://modrinth.com/mod/Villager-Retaliation/
mod_issue_tracker=https://github.com/JevenDev/Villager-Retaliation/issues
