org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

java_version=21

# Minecraft Properties
minecraft_version=1.21.1
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Dependency Versions
neo_version=21.1.238
owo_version=0.12.15.1-beta.6+1.21
architectury_version=13.0.8
emi_version=1.1.22+1.21.1
jei_version=19.43.0.393
rei_version=16.0.799
curios_version=9.5.1+1.21.1
accessories_version=1.1.0-beta.51+1.21.1

# ToucanLib
enable_toucanlib=true
useLocalToucanLib=false
toucanlib_version=0.5.0
toucanlib_modrinth_slug=toucan
toucanlib_neoforge_version=0.5.0-neoforge
toucanlib_curse_project_id=1542666
toucanlib_curse_file_id=8089151

# Loader Ranges
minecraft_version_range=[1.21.1]
loader_version_range=[1,)

## Mod Properties
mod_id=villagerretaliation
mod_name=Villager Retaliation!
mod_authors=jvn
mod_license=All Rights Reserved
mod_version=1.0.0-beta.13
maven_group=com.jvn.villagerretaliation
archives_base_name=villager_retaliation
mod_description=It's about time villagers fought back.
mod_display_url=https://modrinth.com/mod/Villager-Retaliation/
mod_issue_tracker=https://github.com/JevenDev/Villager-Retaliation/issues
