package com.jvn.villagerretaliation.scene.executor;

import com.jvn.villagerretaliation.VillagerRetaliation;
import com.jvn.villagerretaliation.api.registry.ExtensionContracts.RecoveryMode;
import com.jvn.villagerretaliation.api.scene.SceneStepExecutor;
import com.jvn.villagerretaliation.api.scene.SceneStepExecutors;
import com.jvn.villagerretaliation.scene.encounter.EncounterInstance;
import com.jvn.villagerretaliation.scene.encounter.EncounterResources;
import com.jvn.villagerretaliation.scene.encounter.EncounterService;
import com.jvn.villagerretaliation.scene.encounter.EncounterTemplate;
import com.jvn.villagerretaliation.scene.runtime.SceneExecutionContext;
import com.jvn.villagerretaliation.scene.runtime.SceneOperationReceipt;
import com.jvn.villagerretaliation.scene.runtime.SceneStepResult;
import net.minecraft.core.BlockPos;
import net.minecraft.resources.ResourceLocation;

public final class EncounterStepExecutors {
    private static boolean registered;private EncounterStepExecutors(){}
    public static synchronized void register(){if(registered)return;register("start_encounter",new Start());register("wait_encounter",new Wait());register("cancel_encounter",new Cancel());register("cleanup_encounter",new Cleanup());registered=true;}
    private static void register(String id,SceneStepExecutor value){SceneStepExecutors.register(VillagerRetaliation.id(id),value);}
    private abstract static class Base implements SceneStepExecutor{public RecoveryMode recoveryMode(){return RecoveryMode.WORLD_RECONCILED;}public SceneStepResult prepare(SceneExecutionContext c){return SceneStepResult.ready();}public SceneStepResult verify(SceneExecutionContext c){return SceneStepResult.complete();}public SceneStepResult reconcile(SceneExecutionContext c){return apply(c);}protected EncounterInstance encounter(SceneExecutionContext c){String id=c.record().durableValues().get("encounter_id");if(id==null)return null;try{return c.repository().encounter(java.util.UUID.fromString(id)).orElse(null);}catch(IllegalArgumentException e){return null;}}}
    private static final class Start extends Base{public SceneStepResult prepare(SceneExecutionContext c){ResourceLocation template=id(c,"template","encounter_template");if(template==null||EncounterResources.template(c.server(),template).isEmpty())return SceneStepResult.fail("encounter_template_missing","unknown encounter template "+template);BlockPos anchor=anchor(c);if(anchor==null)return SceneStepResult.fail("encounter_anchor_missing","encounter requires anchor actor or position");c.record().putDurableValue("anchor_x",Integer.toString(anchor.getX()));c.record().putDurableValue("anchor_y",Integer.toString(anchor.getY()));c.record().putDurableValue("anchor_z",Integer.toString(anchor.getZ()));c.record().putDurableValue("anchor_dimension",dimension(c).toString());return SceneStepResult.ready();}
        public SceneStepResult apply(SceneExecutionContext c){ResourceLocation templateId=id(c,"template","encounter_template");EncounterTemplate template=EncounterResources.template(c.server(),templateId).orElse(null);if(template==null)return SceneStepResult.fail("encounter_template_missing","encounter template disappeared");BlockPos anchor=new BlockPos(integer(c,"anchor_x"),integer(c,"anchor_y"),integer(c,"anchor_z"));var started=c.repository().startEncounter(template,c.instance(),c.operationId("encounter"),ResourceLocation.parse(c.record().durableValues().get("anchor_dimension")),anchor,string(c,"difficulty","normal"));EncounterInstance encounter=started.encounter();c.record().putDurableValue("encounter_id",encounter.id().toString());SceneOperationReceipt receipt=c.prepareReceipt("encounter",SceneOperationReceipt.Kind.ENCOUNTER_CREATION);var result=EncounterService.reconcileSpawn(c.server(),c.repository(),encounter,template);if(result.status()==EncounterService.Status.WAITING)return SceneStepResult.waitUntil(c.gameTime()+20,result.diagnostic());if(result.status()==EncounterService.Status.FAILED)return SceneStepResult.fail("encounter_spawn_failed",result.diagnostic());receipt.applied(c.gameTime(),"encounter="+encounter.id());receipt.completed(c.gameTime(),"encounter="+encounter.id());return SceneStepResult.applied();}}
    private static final class Wait extends Base{public SceneStepResult apply(SceneExecutionContext c){EncounterInstance e=encounter(c);if(e==null)return SceneStepResult.block("encounter_missing","wait_encounter has no persisted encounter id");var result=EncounterService.refresh(c.server(),c.repository(),e);return switch(result.status()){case COMPLETED->SceneStepResult.applied();case FAILED->SceneStepResult.fail("encounter_failed",result.diagnostic());case ACTIVE,WAITING->SceneStepResult.waitUntil(c.gameTime()+20,result.diagnostic());};}}
    private static final class Cancel extends Base{public SceneStepResult apply(SceneExecutionContext c){EncounterInstance e=encounter(c);if(e==null)return SceneStepResult.skip();e.cancel();c.repository().changed();return SceneStepResult.applied();}}
    private static final class Cleanup extends Base{public SceneStepResult apply(SceneExecutionContext c){EncounterInstance e=encounter(c);if(e==null)return SceneStepResult.skip();var result=EncounterService.cleanup(c.server(),c.repository(),e,bool(c,"force_remove",false));return result.status()==EncounterService.Status.WAITING?SceneStepResult.waitUntil(c.gameTime()+20,result.diagnostic()):SceneStepResult.applied();}}
    private static ResourceLocation id(SceneExecutionContext c,String...keys){for(String k:keys){String v=string(c,k,"");if(!v.isBlank())return ResourceLocation.tryParse(v);}return null;}private static String string(SceneExecutionContext c,String key,String f){return c.step().parameters().has(key)?c.step().parameters().get(key).getAsString():f;}private static boolean bool(SceneExecutionContext c,String key,boolean f){return c.step().parameters().has(key)?c.step().parameters().get(key).getAsBoolean():f;}private static int integer(SceneExecutionContext c,String key){return Integer.parseInt(c.record().durableValues().get(key));}private static ResourceLocation dimension(SceneExecutionContext c){String actor=string(c,"anchor_actor","");var binding=c.instance().actorBindings().get(actor);return binding!=null&&binding.lastDimension()!=null?binding.lastDimension():ResourceLocation.tryParse(string(c,"dimension","minecraft:overworld"));}private static BlockPos anchor(SceneExecutionContext c){String actor=string(c,"anchor_actor","");var binding=c.instance().actorBindings().get(actor);if(binding!=null&&binding.lastPosition()!=null)return binding.lastPosition();if(c.step().parameters().has("x")&&c.step().parameters().has("y")&&c.step().parameters().has("z"))return new BlockPos(c.step().parameters().get("x").getAsInt(),c.step().parameters().get("y").getAsInt(),c.step().parameters().get("z").getAsInt());return null;}
}
