package com.jvn.villagerretaliation.scene;

import com.jvn.villagerretaliation.api.registry.ExtensionContracts.RecoveryMode;
import com.jvn.villagerretaliation.api.scene.SceneStepExecutors;
import com.jvn.villagerretaliation.scene.actor.SceneActorBinding;
import com.jvn.villagerretaliation.scene.actor.SceneActorBindingService;
import com.jvn.villagerretaliation.scene.encounter.EncounterService;
import com.jvn.villagerretaliation.scene.persistence.SceneSavedData;
import com.jvn.villagerretaliation.scene.runtime.SceneAuditEntry;
import com.jvn.villagerretaliation.scene.runtime.SceneInstance;
import com.jvn.villagerretaliation.scene.runtime.SceneState;
import com.jvn.villagerretaliation.scene.runtime.SceneTransitionService;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.entity.Entity;

public final class SceneOperatorService {
    private SceneOperatorService(){}
    public static List<String> inspect(ServerLevel level,UUID id){SceneSavedData data=SceneSavedData.get(level);SceneInstance s=data.get(id).orElse(null);if(s==null)return List.of("Scene not found: "+id);List<String> lines=new ArrayList<>();lines.add("scene="+s.id()+" resource="+s.sceneId()+" state="+s.state()+" step="+s.currentStep());lines.add("owner="+s.owner().stableKey()+" quest="+s.owningQuestId()+" hash="+s.definitionHash());lines.add("actors="+s.actorBindings().keySet()+" receipts="+s.receipts().size()+" cleanup="+s.cleanupStatus()+" cleanupRetryAt="+s.cleanupRetryAt());if(!s.cleanupDiagnostic().isBlank())lines.add("cleanupDiagnostic="+s.cleanupDiagnostic());for(var encounter:data.encounters())if(encounter.sceneId().equals(id))lines.add("encounter="+encounter.id()+" state="+encounter.state()+" sourceTemplate="+encounter.sourceTemplateId()+" variant="+encounter.selectedVariantId()+" resolvedTemplate="+encounter.templateId()+" variantSeed="+encounter.variantSeed()+" attempt="+encounter.attemptCount()+" retryAt="+encounter.retryAt()+" retryAction="+encounter.pendingFailureAction()+" retryCause="+encounter.failureCause()+" objectives="+encounter.completedObjectives()+" failed="+encounter.failedObjectives()+" since="+encounter.objectiveSince()+" allies="+encounter.allies()+" allyGate="+encounter.allyCompletionBlocked()+" guidanceNotified="+encounter.guidanceNotified()+" discovered="+encounter.guidanceDiscovered()+" arrived="+encounter.guidanceArrived()+" guidanceNextAt="+encounter.guidanceNextAt()+" guidanceCleared="+encounter.guidanceCleared()+" completionRewardEligible="+encounter.completionRewardEligible()+" claimedTrophySpawns="+encounter.claimedTrophySpawns());if(!s.diagnostic().isBlank())lines.add("diagnostic="+s.failureCode()+": "+s.diagnostic());return lines;}
    public static List<String> trace(ServerLevel level,UUID id){List<String> lines=new ArrayList<>(inspect(level,id));SceneSavedData data=SceneSavedData.get(level);data.get(id).ifPresent(scene->scene.stepRecords().values().forEach(r->lines.add("step="+r.stepId()+" type="+r.stepType()+" status="+r.status()+" attempts="+r.attempts()+" choice="+r.chosenTransition())));data.auditEntries().stream().filter(a->id.equals(a.sceneId())).forEach(a->lines.add("audit="+a.gameTime()+" "+a.operatorIdentity()+" "+a.reason()+" "+a.priorState()+"->"+a.newState()));return List.copyOf(lines);}
    public static Result rebind(ServerLevel level,UUID sceneId,String alias,Entity replacement,String reason,String operator){SceneSavedData data=SceneSavedData.get(level);SceneInstance scene=data.get(sceneId).orElse(null);var definition=scene==null?null:SceneResources.scene(level.getServer(),scene.sceneId()).orElse(null);if(scene==null||definition==null||replacement==null)return Result.fail("scene, definition, or replacement is missing");var declaration=definition.actors().get(alias);var current=scene.actorBindings().get(alias);if(declaration==null||current==null)return Result.fail("actor alias is not currently bound");SceneActorBinding candidate=SceneActorBinding.entity(alias,declaration.actorType(),replacement.getUUID(),current.sourceType(),replacement.level().dimension().location(),replacement.blockPosition(),replacement.getDisplayName().getString(),true);var result=SceneActorBindingService.rebind(declaration,current,candidate,SceneActorBindingService.RebindKind.OPERATOR,level.getGameTime(),reason,operator);if(!result.accepted())return Result.fail(result.diagnostic());scene.replaceBinding(alias,result.binding());audit(data,scene,alias,current.targetIdentity(),result.binding().targetIdentity(),reason,level.getGameTime(),operator);SceneRuntime.wake(level.getServer(),scene);return Result.ok("actor rebound");}
    public static Result retry(ServerLevel level,UUID id,String reason,String operator){SceneSavedData data=SceneSavedData.get(level);SceneInstance scene=data.get(id).orElse(null);if(scene==null)return Result.fail("scene not found");var definition=SceneResources.scene(level.getServer(),scene.sceneId()).orElse(null);var step=definition==null?null:definition.steps().get(scene.currentStep());var executor=step==null?null:SceneStepExecutors.get(step.type()).orElse(null);if(executor==null||executor.recoveryMode()==RecoveryMode.UNSAFE_BLOCK)return Result.fail("current step has no provably safe retry");String prior=scene.state().name();var record=scene.stepRecords().get(scene.currentStep());if(record!=null)record.resetForRetry();scene.retry();audit(data,scene,"",prior,scene.state().name(),reason,level.getGameTime(),operator);SceneRuntime.wake(level.getServer(),scene);return Result.ok("scene retry queued");}
    public static Result cancel(ServerLevel level,UUID id,String reason,String operator){SceneSavedData data=SceneSavedData.get(level);SceneInstance scene=data.get(id).orElse(null);if(scene==null)return Result.fail("scene not found");String prior=scene.state().name();var definition=SceneResources.scene(level.getServer(),scene.sceneId()).orElse(null);SceneTransitionService.cancel(data,scene,definition,"operator_cancel",reason,level.getGameTime());audit(data,scene,"",prior,scene.state().name(),reason,level.getGameTime(),operator);return Result.ok("scene cancellation policy applied");}
    public static Result forceCleanup(ServerLevel level,UUID encounterId,String reason,String operator){SceneSavedData data=SceneSavedData.get(level);var encounter=data.encounter(encounterId).orElse(null);if(encounter==null)return Result.fail("encounter not found");String prior=encounter.state().name();EncounterService.cleanup(level.getServer(),data,encounter,true);SceneInstance scene=data.get(encounter.sceneId()).orElse(null);if(scene!=null)audit(data,scene,"",prior,encounter.state().name(),reason,level.getGameTime(),operator);return Result.ok("encounter cleanup requested");}
    public static Result resume(ServerLevel level,UUID id,String reason,String operator){SceneSavedData data=SceneSavedData.get(level);SceneInstance scene=data.get(id).orElse(null);if(scene==null||scene.state()!=SceneState.BLOCKED||!scene.repairableBlocked())return Result.fail("scene is not blocked in a repairable policy state");String prior=scene.state().name();scene.retry();audit(data,scene,"",prior,scene.state().name(),reason,level.getGameTime(),operator);SceneRuntime.wake(level.getServer(),scene);return Result.ok("scene resumed");}
    private static void audit(SceneSavedData data,SceneInstance scene,String actor,String prior,String next,String reason,long time,String operator){data.audit(new SceneAuditEntry(scene.id(),actor,prior,next,reason,time,operator));}
    public record Result(boolean success,String message){static Result ok(String m){return new Result(true,m);}static Result fail(String m){return new Result(false,m);}}
}
