package com.jvn.villagerretaliation.scene.encounter;

import com.jvn.villagerretaliation.scene.persistence.SceneSavedData;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import net.minecraft.core.BlockPos;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.resources.ResourceKey;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.level.levelgen.Heightmap;
import net.minecraft.world.phys.AABB;

public final class EncounterService {
    private static final String OWNER="VillagerRetaliationEncounter";private static final String SCENE="VillagerRetaliationScene";
    private EncounterService(){}
    public static Result reconcileSpawn(MinecraftServer server,SceneSavedData data,EncounterInstance encounter,EncounterTemplate template){ServerLevel level=level(server,encounter);if(level==null||!level.hasChunkAt(encounter.anchor()))return Result.waiting("spawn anchor chunk is unloaded");
        // Recover entities spawned before their UUID list was saved, but only inside the bounded anchor area and by exact durable owner tag.
        for(Entity entity:level.getEntities((Entity)null,new AABB(encounter.anchor()).inflate(template.spawnRadius()+2),value->ownedBy(value,encounter.id())))if(!encounter.spawned().contains(entity.getUUID()))encounter.addSpawn(entity.getUUID());
        int remaining=encounter.expectedCount()-encounter.spawned().size();if(remaining<=0){data.changed();return Result.active();}
        List<net.minecraft.resources.ResourceLocation> desired=desiredTypes(template,encounter.partySize());int start=encounter.spawned().size();
        for(int index=start;index<desired.size();index++){Entity entity=spawn(level,desired.get(index),encounter,template,index);if(entity==null){encounter.fail("safe placement exhausted after "+template.placementAttempts()+" attempts for member "+index);data.changed();return Result.failed(encounter.diagnostic());}encounter.addSpawn(entity.getUUID());data.changed();}
        return Result.active();}
    public static Result refresh(MinecraftServer server,SceneSavedData data,EncounterInstance encounter){EncounterTemplate template=EncounterResources.template(server,encounter.templateId()).orElse(null);if(template==null){encounter.fail("encounter template is unavailable");data.changed();return Result.failed(encounter.diagnostic());}if(encounter.state()==EncounterInstance.EncounterState.PREPARED||encounter.state()==EncounterInstance.EncounterState.SPAWNING)return reconcileSpawn(server,data,encounter,template);encounter.checkComplete();data.changed();return encounter.state()==EncounterInstance.EncounterState.COMPLETED?Result.completed():encounter.state()==EncounterInstance.EncounterState.FAILED?Result.failed(encounter.diagnostic()):Result.active();}
    public static Result cleanup(MinecraftServer server,SceneSavedData data,EncounterInstance encounter,boolean forceRemove){encounter.cleaning();boolean waiting=false;for(UUID id:encounter.spawned()){if(encounter.defeated().contains(id))continue;Entity entity=find(server,id);if(entity==null){waiting=true;continue;}if(forceRemove||encounter.cleanupPolicy()==EncounterTemplate.CleanupPolicy.REMOVE_SURVIVORS)entity.discard();else release(entity);}if(waiting&&(forceRemove||encounter.cleanupPolicy()==EncounterTemplate.CleanupPolicy.REMOVE_SURVIVORS)){data.changed();return Result.waiting("owned encounter entities are unloaded; cleanup will resume when they return");}if(encounter.cleanupPolicy()==EncounterTemplate.CleanupPolicy.PRESERVE_IN_WORLD&&!forceRemove)encounter.released();else encounter.cleaned();data.changed();return Result.completed();}
    public static void onDeath(LivingEntity entity){CompoundTag persistent=entity.getPersistentData();if(!persistent.hasUUID(OWNER)||!(entity.level() instanceof ServerLevel level))return;SceneSavedData data=SceneSavedData.get(level);data.encounter(persistent.getUUID(OWNER)).ifPresent(encounter->{encounter.defeated(entity.getUUID());data.changed();});}
    public static void onEntityJoin(Entity entity){CompoundTag persistent=entity.getPersistentData();if(!persistent.hasUUID(OWNER)||!(entity.level() instanceof ServerLevel level))return;SceneSavedData data=SceneSavedData.get(level);EncounterInstance encounter=data.encounter(persistent.getUUID(OWNER)).orElse(null);if(encounter==null)return;if(encounter.state()==EncounterInstance.EncounterState.RELEASED)release(entity);else if(encounter.state()==EncounterInstance.EncounterState.CLEANED)entity.discard();}
    private static Entity spawn(ServerLevel level,net.minecraft.resources.ResourceLocation typeId,EncounterInstance encounter,EncounterTemplate template,int index){EntityType<?> type=BuiltInRegistries.ENTITY_TYPE.get(typeId);for(int attempt=0;attempt<template.placementAttempts();attempt++){int seed=Math.floorMod(encounter.id().hashCode()*31+index*17+attempt*13,template.spawnRadius()*template.spawnRadius()*4);int dx=seed%(template.spawnRadius()*2+1)-template.spawnRadius();int dz=(seed/(template.spawnRadius()*2+1))%(template.spawnRadius()*2+1)-template.spawnRadius();BlockPos horizontal=encounter.anchor().offset(dx,0,dz);if(!level.hasChunkAt(horizontal))continue;int y=level.getHeight(Heightmap.Types.MOTION_BLOCKING_NO_LEAVES,horizontal.getX(),horizontal.getZ());BlockPos pos=new BlockPos(horizontal.getX(),y,horizontal.getZ());Entity entity=type.create(level);if(entity==null)continue;entity.moveTo(pos.getX()+.5,pos.getY(),pos.getZ()+.5,0,0);if(!level.noCollision(entity)){entity.discard();continue;}entity.getPersistentData().putUUID(OWNER,encounter.id());entity.getPersistentData().putUUID(SCENE,encounter.sceneId());entity.getPersistentData().putInt("VillagerRetaliationSpawnGeneration",encounter.spawnGeneration());if(level.addFreshEntity(entity))return entity;}return null;}
    private static List<net.minecraft.resources.ResourceLocation> desiredTypes(EncounterTemplate template,int partySize){List<net.minecraft.resources.ResourceLocation> values=new ArrayList<>();for(var member:template.members())for(int i=0;i<member.count();i++)values.add(member.entityType());int extra=template.scaledCount(partySize)-values.size();for(int i=0;i<extra;i++)values.add(template.members().getFirst().entityType());return values;}
    private static ServerLevel level(MinecraftServer server,EncounterInstance e){return server.getLevel(ResourceKey.create(net.minecraft.core.registries.Registries.DIMENSION,e.anchorDimension()));}private static Entity find(MinecraftServer server,UUID id){for(ServerLevel level:server.getAllLevels()){Entity e=level.getEntity(id);if(e!=null)return e;}return null;}private static boolean ownedBy(Entity entity,UUID id){return entity.getPersistentData().hasUUID(OWNER)&&id.equals(entity.getPersistentData().getUUID(OWNER));}private static void release(Entity entity){entity.getPersistentData().remove(OWNER);entity.getPersistentData().remove(SCENE);entity.getPersistentData().remove("VillagerRetaliationSpawnGeneration");}
    public record Result(Status status,String diagnostic){public static Result active(){return new Result(Status.ACTIVE,"");}public static Result waiting(String m){return new Result(Status.WAITING,m);}public static Result completed(){return new Result(Status.COMPLETED,"");}public static Result failed(String m){return new Result(Status.FAILED,m);}}public enum Status{ACTIVE,WAITING,COMPLETED,FAILED}
}
