package com.jvn.villagerretaliation.scene.encounter;

import com.jvn.villagerretaliation.util.NbtDataUtil;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.UUID;
import net.minecraft.core.BlockPos;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.ListTag;
import net.minecraft.nbt.StringTag;
import net.minecraft.nbt.Tag;
import net.minecraft.resources.ResourceLocation;

public final class EncounterInstance {
    private final UUID id;private final ResourceLocation templateId;private final UUID sceneId;private final String operationId;
    private final String ownerKey;private final Set<UUID> participants;private final ResourceLocation anchorDimension;private final BlockPos anchor;
    private final Set<UUID> spawned=new LinkedHashSet<>();private final Set<UUID> defeated=new LinkedHashSet<>();private final Set<UUID> missing=new LinkedHashSet<>();
    private int spawnGeneration;private final int partySize;private final String difficulty;private EncounterState state;private final EncounterTemplate.CleanupPolicy cleanupPolicy;private final EncounterTemplate.CompletionCondition completionCondition;private int expectedCount;private String diagnostic="";
    public EncounterInstance(UUID id,ResourceLocation templateId,UUID sceneId,String operationId,String ownerKey,Set<UUID> participants,ResourceLocation dimension,BlockPos anchor,int partySize,String difficulty,EncounterTemplate.CleanupPolicy cleanup,EncounterTemplate.CompletionCondition completion,int expectedCount){this.id=id;this.templateId=templateId;this.sceneId=sceneId;this.operationId=operationId;this.ownerKey=ownerKey;this.participants=new LinkedHashSet<>(participants);this.anchorDimension=dimension;this.anchor=anchor.immutable();this.partySize=Math.max(1,partySize);this.difficulty=difficulty==null?"normal":difficulty;this.cleanupPolicy=cleanup;this.completionCondition=completion;this.expectedCount=expectedCount;this.state=EncounterState.PREPARED;}
    public UUID id(){return id;}public ResourceLocation templateId(){return templateId;}public UUID sceneId(){return sceneId;}public String operationId(){return operationId;}public String ownerKey(){return ownerKey;}public Set<UUID> participants(){return Set.copyOf(participants);}public ResourceLocation anchorDimension(){return anchorDimension;}public BlockPos anchor(){return anchor;}public Set<UUID> spawned(){return Set.copyOf(spawned);}public Set<UUID> defeated(){return Set.copyOf(defeated);}public Set<UUID> missing(){return Set.copyOf(missing);}public int spawnGeneration(){return spawnGeneration;}public int partySize(){return partySize;}public String difficulty(){return difficulty;}public EncounterState state(){return state;}public EncounterTemplate.CleanupPolicy cleanupPolicy(){return cleanupPolicy;}public EncounterTemplate.CompletionCondition completionCondition(){return completionCondition;}public int expectedCount(){return expectedCount;}public String diagnostic(){return diagnostic;}
    public void addSpawn(UUID entity){spawned.add(entity);missing.remove(entity);state=EncounterState.ACTIVE;}public void nextGeneration(){spawnGeneration++;}public void defeated(UUID entity){if(spawned.contains(entity)){defeated.add(entity);missing.remove(entity);checkComplete();}}public void missing(UUID entity){if(spawned.contains(entity)&&!defeated.contains(entity))missing.add(entity);}public void replaceMissing(UUID oldId,UUID newId){missing.remove(oldId);spawned.remove(oldId);spawned.add(newId);spawnGeneration++;}public void cancel(){state=EncounterState.CANCELLED;}public void cleaning(){state=EncounterState.CLEANING_UP;}public void cleaned(){state=EncounterState.CLEANED;}public void fail(String message){state=EncounterState.FAILED;diagnostic=message;}public void released(){state=EncounterState.RELEASED;}public void checkComplete(){int gone=defeated.size()+(completionCondition==EncounterTemplate.CompletionCondition.ALL_GONE?missing.size():0);if(gone>=expectedCount)state=EncounterState.COMPLETED;}
    public CompoundTag save(){CompoundTag t=new CompoundTag();t.putUUID("Id",id);t.putString("Template",templateId.toString());t.putUUID("Scene",sceneId);t.putString("Operation",operationId);t.putString("Owner",ownerKey);t.putString("Dimension",anchorDimension.toString());NbtDataUtil.putBlockPos(t,"Anchor",anchor);t.put("Participants",uuids(participants));t.put("Spawned",uuids(spawned));t.put("Defeated",uuids(defeated));t.put("Missing",uuids(missing));t.putInt("SpawnGeneration",spawnGeneration);t.putInt("PartySize",partySize);t.putString("Difficulty",difficulty);t.putString("State",state.name());t.putString("CleanupPolicy",cleanupPolicy.name());t.putString("CompletionCondition",completionCondition.name());t.putInt("ExpectedCount",expectedCount);t.putString("Diagnostic",diagnostic);return t;}
    public static EncounterInstance load(CompoundTag t){EncounterInstance v=new EncounterInstance(t.getUUID("Id"),ResourceLocation.parse(t.getString("Template")),t.getUUID("Scene"),t.getString("Operation"),t.getString("Owner"),readUuids(t,"Participants"),ResourceLocation.parse(t.getString("Dimension")),NbtDataUtil.readBlockPos(t,"Anchor").orElse(BlockPos.ZERO),t.getInt("PartySize"),t.getString("Difficulty"),EncounterTemplate.CleanupPolicy.valueOf(t.getString("CleanupPolicy")),EncounterTemplate.CompletionCondition.valueOf(t.getString("CompletionCondition")),t.getInt("ExpectedCount"));v.spawned.addAll(readUuids(t,"Spawned"));v.defeated.addAll(readUuids(t,"Defeated"));v.missing.addAll(readUuids(t,"Missing"));v.spawnGeneration=t.getInt("SpawnGeneration");v.state=EncounterState.valueOf(t.getString("State"));v.diagnostic=t.getString("Diagnostic");return v;}
    private static ListTag uuids(Set<UUID> values){ListTag t=new ListTag();values.forEach(v->t.add(StringTag.valueOf(v.toString())));return t;}private static Set<UUID> readUuids(CompoundTag t,String key){Set<UUID> values=new LinkedHashSet<>();for(Tag raw:t.getList(key,Tag.TAG_STRING))try{values.add(UUID.fromString(raw.getAsString()));}catch(IllegalArgumentException ignored){}return values;}
    public enum EncounterState{PREPARED,SPAWNING,ACTIVE,COMPLETED,FAILED,CANCELLED,CLEANING_UP,CLEANED,RELEASED}
}
