package com.jvn.villagerretaliation.scene.encounter;

import com.jvn.villagerretaliation.util.NbtDataUtil;
import java.util.LinkedHashSet;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import net.minecraft.core.BlockPos;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.ListTag;
import net.minecraft.nbt.StringTag;
import net.minecraft.nbt.Tag;
import net.minecraft.resources.ResourceLocation;

public final class EncounterInstance {
    private final UUID id;private final ResourceLocation templateId;private final UUID sceneId;private final String operationId;
    private final String ownerKey;private final Set<UUID> participants;private final ResourceLocation anchorDimension;private final BlockPos anchor;
    private final Set<UUID> spawned=new LinkedHashSet<>();private final Set<UUID> defeated=new LinkedHashSet<>();private final Set<UUID> missing=new LinkedHashSet<>();
    private final Map<UUID,Long> leaveDeadlines=new LinkedHashMap<>();private final Set<UUID> leaveWarned=new LinkedHashSet<>();private final Map<UUID,Long> mobDeadlines=new LinkedHashMap<>();private boolean areaPaused;
    private int currentWaveIndex;private String currentWaveId="";private final Set<String> startedWaves=new LinkedHashSet<>();private final Set<String> firedWaveHooks=new LinkedHashSet<>();
    private int spawnGeneration;private final int partySize;private final String difficulty;private EncounterState state;private final EncounterTemplate.CleanupPolicy cleanupPolicy;private final EncounterTemplate.CompletionCondition completionCondition;private int expectedCount;private long nextWaveAt;private boolean locationNotified;private String diagnostic="";
    public EncounterInstance(UUID id,ResourceLocation templateId,UUID sceneId,String operationId,String ownerKey,Set<UUID> participants,ResourceLocation dimension,BlockPos anchor,int partySize,String difficulty,EncounterTemplate.CleanupPolicy cleanup,EncounterTemplate.CompletionCondition completion,int expectedCount){this.id=id;this.templateId=templateId;this.sceneId=sceneId;this.operationId=operationId;this.ownerKey=ownerKey;this.participants=new LinkedHashSet<>(participants);this.anchorDimension=dimension;this.anchor=anchor.immutable();this.partySize=Math.max(1,partySize);this.difficulty=difficulty==null?"normal":difficulty;this.cleanupPolicy=cleanup;this.completionCondition=completion;this.expectedCount=expectedCount;this.state=EncounterState.PREPARED;}
    public UUID id(){return id;}public ResourceLocation templateId(){return templateId;}public UUID sceneId(){return sceneId;}public String operationId(){return operationId;}public String ownerKey(){return ownerKey;}public Set<UUID> participants(){return Set.copyOf(participants);}public ResourceLocation anchorDimension(){return anchorDimension;}public BlockPos anchor(){return anchor;}public Set<UUID> spawned(){return Set.copyOf(spawned);}public Set<UUID> defeated(){return Set.copyOf(defeated);}public Set<UUID> missing(){return Set.copyOf(missing);}public Map<UUID,Long> leaveDeadlines(){return Map.copyOf(leaveDeadlines);}public Set<UUID> leaveWarned(){return Set.copyOf(leaveWarned);}public Map<UUID,Long> mobDeadlines(){return Map.copyOf(mobDeadlines);}public boolean areaPaused(){return areaPaused;}public int currentWaveIndex(){return currentWaveIndex;}public String currentWaveId(){return currentWaveId;}public Set<String> startedWaves(){return Set.copyOf(startedWaves);}public Set<String> firedWaveHooks(){return Set.copyOf(firedWaveHooks);}public int spawnGeneration(){return spawnGeneration;}public int partySize(){return partySize;}public String difficulty(){return difficulty;}public EncounterState state(){return state;}public EncounterTemplate.CleanupPolicy cleanupPolicy(){return cleanupPolicy;}public EncounterTemplate.CompletionCondition completionCondition(){return completionCondition;}public int expectedCount(){return expectedCount;}public long nextWaveAt(){return nextWaveAt;}public boolean locationNotified(){return locationNotified;}public String diagnostic(){return diagnostic;}
    public void addSpawn(UUID entity){spawned.add(entity);missing.remove(entity);state=EncounterState.ACTIVE;}public void nextGeneration(){spawnGeneration++;}public void scheduleNextWave(long gameTime){nextWaveAt=Math.max(0L,gameTime);}public void markLocationNotified(){locationNotified=true;}public void defeated(UUID entity){if(spawned.contains(entity)){defeated.add(entity);missing.remove(entity);checkComplete();}}public void missing(UUID entity){if(spawned.contains(entity)&&!defeated.contains(entity))missing.add(entity);}public void replaceMissing(UUID oldId,UUID newId){missing.remove(oldId);spawned.remove(oldId);spawned.add(newId);spawnGeneration++;}public void cancel(){state=EncounterState.CANCELLED;}public void cleaning(){state=EncounterState.CLEANING_UP;}public void cleaned(){state=EncounterState.CLEANED;}public void fail(String message){state=EncounterState.FAILED;diagnostic=message;}public void released(){state=EncounterState.RELEASED;}public void checkComplete(){int gone=defeated.size()+(completionCondition==EncounterTemplate.CompletionCondition.ALL_GONE?missing.size():0);if(gone>=expectedCount)state=EncounterState.COMPLETED;}
    public void setLeaveDeadline(UUID player,long deadline){leaveDeadlines.put(player,deadline);}public void clearLeave(UUID player){leaveDeadlines.remove(player);leaveWarned.remove(player);}public void markLeaveWarned(UUID player){leaveWarned.add(player);}public void setMobDeadline(UUID mob,long deadline){mobDeadlines.put(mob,deadline);}public void clearMobDeadline(UUID mob){mobDeadlines.remove(mob);}public void setAreaPaused(boolean paused){areaPaused=paused;}
    public void initializeWave(int index,String waveId){if(currentWaveId.isBlank()){currentWaveIndex=Math.max(0,index);currentWaveId=waveId==null?"":waveId;}}public void advanceWave(int index,String waveId){currentWaveIndex=index;currentWaveId=waveId;nextWaveAt=0L;}public boolean markWaveStarted(String id){return startedWaves.add(id);}public boolean markWaveHookFired(String id){return firedWaveHooks.add(id);}
    public CompoundTag save(){CompoundTag t=new CompoundTag();t.putUUID("Id",id);t.putString("Template",templateId.toString());t.putUUID("Scene",sceneId);t.putString("Operation",operationId);t.putString("Owner",ownerKey);t.putString("Dimension",anchorDimension.toString());NbtDataUtil.putBlockPos(t,"Anchor",anchor);t.put("Participants",uuids(participants));t.put("Spawned",uuids(spawned));t.put("Defeated",uuids(defeated));t.put("Missing",uuids(missing));t.put("LeaveDeadlines",deadlines(leaveDeadlines));t.put("LeaveWarned",uuids(leaveWarned));t.put("MobDeadlines",deadlines(mobDeadlines));t.putBoolean("AreaPaused",areaPaused);t.putInt("CurrentWaveIndex",currentWaveIndex);t.putString("CurrentWaveId",currentWaveId);t.put("StartedWaves",strings(startedWaves));t.put("FiredWaveHooks",strings(firedWaveHooks));t.putInt("SpawnGeneration",spawnGeneration);t.putInt("PartySize",partySize);t.putString("Difficulty",difficulty);t.putString("State",state.name());t.putString("CleanupPolicy",cleanupPolicy.name());t.putString("CompletionCondition",completionCondition.name());t.putInt("ExpectedCount",expectedCount);t.putLong("NextWaveAt",nextWaveAt);t.putBoolean("LocationNotified",locationNotified);t.putString("Diagnostic",diagnostic);return t;}
    public static EncounterInstance load(CompoundTag t){EncounterInstance v=new EncounterInstance(t.getUUID("Id"),ResourceLocation.parse(t.getString("Template")),t.getUUID("Scene"),t.getString("Operation"),t.getString("Owner"),readUuids(t,"Participants"),ResourceLocation.parse(t.getString("Dimension")),NbtDataUtil.readBlockPos(t,"Anchor").orElse(BlockPos.ZERO),t.getInt("PartySize"),t.getString("Difficulty"),EncounterTemplate.CleanupPolicy.valueOf(t.getString("CleanupPolicy")),EncounterTemplate.CompletionCondition.valueOf(t.getString("CompletionCondition")),t.getInt("ExpectedCount"));v.spawned.addAll(readUuids(t,"Spawned"));v.defeated.addAll(readUuids(t,"Defeated"));v.missing.addAll(readUuids(t,"Missing"));v.leaveDeadlines.putAll(readDeadlines(t,"LeaveDeadlines"));v.leaveWarned.addAll(readUuids(t,"LeaveWarned"));v.mobDeadlines.putAll(readDeadlines(t,"MobDeadlines"));v.areaPaused=t.getBoolean("AreaPaused");v.currentWaveIndex=t.getInt("CurrentWaveIndex");v.currentWaveId=t.getString("CurrentWaveId");v.startedWaves.addAll(readStrings(t,"StartedWaves"));v.firedWaveHooks.addAll(readStrings(t,"FiredWaveHooks"));v.spawnGeneration=t.getInt("SpawnGeneration");v.nextWaveAt=t.getLong("NextWaveAt");v.locationNotified=t.getBoolean("LocationNotified");v.state=EncounterState.valueOf(t.getString("State"));v.diagnostic=t.getString("Diagnostic");return v;}
    private static ListTag uuids(Set<UUID> values){ListTag t=new ListTag();values.forEach(v->t.add(StringTag.valueOf(v.toString())));return t;}private static Set<UUID> readUuids(CompoundTag t,String key){Set<UUID> values=new LinkedHashSet<>();for(Tag raw:t.getList(key,Tag.TAG_STRING))try{values.add(UUID.fromString(raw.getAsString()));}catch(IllegalArgumentException ignored){}return values;}
    private static ListTag deadlines(Map<UUID,Long> values){ListTag list=new ListTag();values.forEach((id,deadline)->{CompoundTag entry=new CompoundTag();entry.putUUID("Id",id);entry.putLong("Deadline",deadline);list.add(entry);});return list;}private static Map<UUID,Long> readDeadlines(CompoundTag t,String key){Map<UUID,Long> values=new LinkedHashMap<>();for(Tag raw:t.getList(key,Tag.TAG_COMPOUND)){CompoundTag entry=(CompoundTag)raw;if(entry.hasUUID("Id"))values.put(entry.getUUID("Id"),entry.getLong("Deadline"));}return values;}
    private static ListTag strings(Set<String> values){ListTag list=new ListTag();values.forEach(value->list.add(StringTag.valueOf(value)));return list;}private static Set<String> readStrings(CompoundTag t,String key){Set<String> values=new LinkedHashSet<>();for(Tag raw:t.getList(key,Tag.TAG_STRING))values.add(raw.getAsString());return values;}
    public enum EncounterState{PREPARED,SPAWNING,ACTIVE,COMPLETED,FAILED,CANCELLED,CLEANING_UP,CLEANED,RELEASED}
}
