modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="${mod_issue_tracker}"

[[mixins]]
config="${mod_id}.mixins.json"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="villager_retaliation_cover.png"
authors="${mod_authors}"
displayURL="${mod_display_url}"
description='''
${mod_description}
'''

[[dependencies."${mod_id}"]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

${neoforge_owo_dependency}

${neoforge_architectury_dependency}

${neoforge_toucanlib_dependency}

[[dependencies."${mod_id}"]]
modId="entity_model_features"
type="optional"
ordering="AFTER"
side="CLIENT"

[[dependencies."${mod_id}"]]
modId="entity_texture_features"
type="optional"
ordering="NONE"
side="CLIENT"

[[dependencies."${mod_id}"]]
modId="secondwind"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
