plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev'
    id 'idea'
}

base {
    archivesName = "${rootProject.archives_base_name}-neoforge-${rootProject.minecraft_version}"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(rootProject.java_version.toInteger())
    withSourcesJar()
}

sourceSets.main.resources {
    srcDir('src/generated/resources')
    exclude('**/*.bbmodel')
    exclude('src/generated/**/.cache')
}

neoForge {
    version = rootProject.neo_version

    parchment {
        mappingsVersion = rootProject.parchment_mappings_version
        minecraftVersion = rootProject.parchment_minecraft_version
    }

    runs {
        client {
            client()
        }

        server {
            server()
            programArgument '--nogui'
        }

        data {
            data()
            programArguments.addAll '--mod', rootProject.mod_id, '--all',
                    '--output', file('src/generated/resources/').absolutePath,
                    '--existing', file('src/main/resources/').absolutePath
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${rootProject.mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    implementation "io.wispforest:owo-lib-neoforge:${rootProject.owo_version}"
    annotationProcessor "io.wispforest:owo-lib-neoforge:${rootProject.owo_version}"

    if (rootProject.enable_toucanlib.toBoolean()) {
        if (rootProject.useLocalToucanLib.toBoolean()) {
            implementation "com.jvn.toucanlib:toucanlib-neoforge-${rootProject.minecraft_version}:${rootProject.toucanlib_version}"
        } else {
            implementation "maven.modrinth:${rootProject.toucanlib_modrinth_slug}:${rootProject.toucanlib_neoforge_version}"
        }
    }
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            minecraft_version      : rootProject.minecraft_version,
            minecraft_version_range: rootProject.minecraft_version_range,
            neo_version            : rootProject.neo_version,
            loader_version_range   : rootProject.loader_version_range,
            toucanlib_version      : rootProject.toucanlib_version,
            owo_version            : rootProject.owo_version,
            mod_id                 : rootProject.mod_id,
            mod_name               : rootProject.mod_name,
            mod_license            : rootProject.mod_license,
            mod_version            : rootProject.mod_version,
            mod_authors            : rootProject.mod_authors,
            mod_description        : rootProject.mod_description,
            mod_display_url        : rootProject.mod_display_url,
            mod_issue_tracker      : rootProject.mod_issue_tracker,
            neoforge_toucanlib_dependency: rootProject.enable_toucanlib.toBoolean()
                    ? """[[dependencies."${rootProject.mod_id}"]]
modId="toucanlib"
type="required"
versionRange="[${rootProject.toucanlib_version},)"
ordering="AFTER"
side="BOTH"
"""
                    : '',
            neoforge_owo_dependency: """[[dependencies."${rootProject.mod_id}"]]
modId="owo"
type="required"
versionRange="[${rootProject.owo_version},)"
ordering="AFTER"
side="BOTH"
""",
    ]
    inputs.properties replaceProperties

    filesMatching('META-INF/neoforge.mods.toml') {
        expand replaceProperties
    }

    filesMatching('pack.mcmeta') {
        expand(mod_name: rootProject.mod_name)
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url = rootProject.file('repo').toURI()
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = rootProject.java_version.toInteger()
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
