import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const syntaxFiles = [
  "tools/datapack-builder/app.js",
  "tools/datapack-builder/backend.js",
  "tools/datapack-builder/build-wiki-snapshot.mjs",
  "tools/quest-builder/app.js",
  "tools/quest-builder/quest-model.js",
  "tools/quest-builder/zip-utils.js",
  "wiki/shared/search.js",
  "wiki/player/app.js",
  "wiki/player/build-data.mjs",
  "wiki/player/content/guides.js",
  "wiki/dev/app.js",
  "wiki/dev/build-data.mjs"
];

const validationScripts = [
  "tools/quest-bundle-baseline.mjs",
  "tools/validate-dialogue-data.mjs",
  "tools/test-built-in-quest-content.mjs",
  "tools/test-quest-v2-tools.mjs",
  "tools/test-datapack-builder-schema.mjs",
  "tools/test-quest-builder-model.mjs",
  "tools/test-quest-builder-zip.mjs",
  "tools/test-quest-builder-output.mjs"
];

const generatedChecks = [
  ["tools/datapack-builder/build-wiki-snapshot.mjs", "--check"],
  ["wiki/player/build-data.mjs", "--check"],
  ["wiki/dev/build-data.mjs", "--check"]
];

const requiredFiles = [
  "tools/datapack-builder/index.html",
  "tools/datapack-builder/styles.css",
  "tools/datapack-builder/app.js",
  "tools/datapack-builder/wiki-snapshot.js",
  "tools/quest-builder/index.html",
  "tools/quest-builder/styles.css",
  "tools/quest-builder/app.js",
  "tools/quest-builder/quest-model.js",
  "tools/quest-builder/zip-utils.js",
  "wiki/shared/search.js",
  "wiki/shared/villager_retaliation_logo.png",
  "wiki/player/index.html",
  "wiki/player/styles.css",
  "wiki/player/app.js",
  "wiki/player/content/guides.js",
  "wiki/player/site-data.js",
  "wiki/dev/index.html",
  "wiki/dev/styles.css",
  "wiki/dev/developer.css",
  "wiki/dev/app.js",
  "wiki/dev/site-data.js",
  "wiki/dev/content/Home.md",
  "wiki/dev/content/Quest-Scene-Runtime.md",
  "wiki/dev/content/Tracked-Villages.md"
];

const generatedArtifacts = [
  "tools/datapack-builder/wiki-snapshot.js",
  "wiki/player/site-data.js",
  "wiki/dev/site-data.js"
];

function runNode(label, args) {
  console.log(`\n[verify] ${label}`);
  const result = spawnSync(process.execPath, args, { cwd: repoRoot, stdio: "inherit" });
  if (result.error) throw result.error;
  if (result.status !== 0) process.exit(result.status ?? 1);
}

for (const file of requiredFiles) {
  if (!existsSync(path.join(repoRoot, file))) {
    console.error(`[verify] Missing required file: ${file}`);
    process.exit(1);
  }
}

for (const file of syntaxFiles) runNode(`syntax ${file}`, ["--check", file]);
for (const script of validationScripts) runNode(script, [script]);
for (const [script, ...args] of generatedChecks) runNode(`${script} ${args.join(" ")}`, [script, ...args]);

for (const file of generatedArtifacts) {
  const source = readFileSync(path.join(repoRoot, file), "utf8");
  if (!source.startsWith("// Generated by ")) {
    console.error(`[verify] Generated artifact is missing its ownership header: ${file}`);
    process.exit(1);
  }
}

console.log("\n[verify] All repository validation passed.");
