package com.jvn.villagerretaliation.dialogue;

public enum DialogueRequestType {
    SMALL_TALK,
    GREETING,
    QUESTION,
    GIFT_PREFERENCES,
    GIFT_ADVICE_FOLLOWUP,
    MAP_REPORT,
    STORY_HINT_REPORT,
    COMBAT_SURVIVAL_REPORT,
    GEAR_REPORT,
    RECRUITMENT_FOLLOWUP,
    CURED_RECOGNITION,
    VILLAGE_EVENT_REPORT,
    APOLOGY,
    VILLAGE_DEFENSE_REPORT,
    STORY,
    SHARE_STORY,
    JOKE,
    INSULT
}
